version: '2'
services:
  libs-builder:
    build : .
    image: malos-vision-android-libs
    command: 
      - /bin/sh
      - -c 
      - |
        cd /opt/src/
        rm -rf android_vision_libs*
        cd caffe-android-lib && \
        git submodule update --init --recursive && \
        ../builder.sh
        
    volumes:
      - .:/opt/src
